inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - app/channels/**/*
    - node_modules/**/*
    - bin/*
    - spec/**/*
    - lib/*
    - db/migrate/*
    - db/*
    - lib/tasks/*
    - public/*
    - tmp/*
    - vendor/**/*
    - config/spring.rb

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# クラスのコメント必須を無視
Documentation:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# 文字リテラルのイミュータブル宣言を無視（freezeになるのはRuby3以降）
Style/FrozenStringLiteralComment:
  Enabled: false

# 行の文字数を制限しない
Metrics/LineLength:
  Enabled: false

#コードのソフトウェアサイズを無視
Metrics/AbcSize:
  Enabled: false

#ブロック内の行数は50まで
Metrics/BlockLength:
  Max: 40